onramp-io/twitch-android-project-2

- app/src/main/java/com/example/voyagerx/MainActivity.kt
> test commit

- app/src/main/java/com/example/voyagerx/MainActivity.kt
> second test commit

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- .idea/misc.xml
- app/src/main/res/layout/launch_overview_card.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- build.gradle
Ticket - https://onramp-training.atlassian.net/browse/TA2-64
This adds the card design, I made some changes based on discussion that aren't in the wireframe.
- Using launch year instead of the launch utc date
- Using mission name instead of rocket name
- Moved year to the end of the card, I thought this made a little more sense stylistically but open to changing
> Event listing card design

- .idea/misc.xml
- app/src/main/java/com/example/voyagerx/LandingPageFragment.kt
- app/src/main/java/com/example/voyagerx/MainActivity.kt
- app/src/main/java/com/example/voyagerx/repository/LaunchRepository.kt
- app/src/main/java/com/example/voyagerx/repository/model/Launch.kt
I created the method `convertLaunches()` to convert the API results to a list of our custom Launch objects.
Jira Ticket: https://onramp-training.atlassian.net/browse/TA2-74
> Convert API Results

- .idea/.gitignore
Added the following files to .gitignore:
`.idea/deploymentTargetDropDown.xml`
`.idea/misc.xml`
> Added idea files to gitignore

- app/build.gradle
- app/src/androidTest/java/com/example/voyagerx/di/InjectionTest.kt
- app/src/androidTest/java/com/example/voyagerx/di/MyTestRunner.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/voyagerx/MainActivity.kt
- app/src/main/java/com/example/voyagerx/VoyagerXApplication.kt
- app/src/main/java/com/example/voyagerx/di/AppModule.kt
- app/src/main/java/com/example/voyagerx/repository/LaunchRepository.kt
- app/src/main/java/com/example/voyagerx/repository/UserRepository.kt
- app/src/main/java/com/example/voyagerx/ui/fragments/landing/LandingPageFragment.kt
- build.gradle
Dependency injection with Dagger Hilt. Added UserRepository class (more methods to come).
> added di with hilt

- .idea/deploymentTargetDropDown.xml
- .idea/misc.xml
- app/src/main/java/com/example/voyagerx/LaunchDetailsFragment.kt
- app/src/main/java/com/example/voyagerx/MainActivity.kt
- app/src/main/java/com/example/voyagerx/adapters/LaunchCarouselAdapter.kt
- app/src/main/res/layout/fragment_launch_details.xml
I used the `PageView` element to contain the image carousel. I created the `LaunchCarouselAdapter` which extends PageAdapter to create the slideshow effect. If there are no photos available, the default SpaceX logo ImageView will be visible.
https://user-images.githubusercontent.com/41392379/166297659-2a9d9e06-2130-4e64-adea-f570ce6cccb5.mov
> Launch Image Carousel

- app/src/main/java/com/example/voyagerx/repository/UserRepository.kt
- app/src/main/java/com/example/voyagerx/repository/database/UserDao.kt
- app/src/main/res/values/strings.xml
Added methods in user repo to login/logout/register/get current user/add & remove fav launches
> added more user repo methods

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/voyagerx/LoginActivity.kt
- app/src/main/java/com/example/voyagerx/LoginFragment.kt
- app/src/main/java/com/example/voyagerx/RegisterFragment.kt
- app/src/main/java/com/example/voyagerx/repository/UserRepository.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/layout/fragment_register.xml
- app/src/main/res/values/strings.xml
Added registration and login functionality. Errors will be displayed via Snackbar. 
I had to changed some of repository methods to suspend functions since database can't be modified on main thread.
https://user-images.githubusercontent.com/103967461/166556041-1b783848-992d-41c9-a4a6-45733e294e01.mov
> Register new account/Login

- app/src/main/java/com/example/voyagerx/LaunchDetailsFragment.kt
- app/src/main/res/layout/fragment_launch_details.xml
- app/src/main/res/values/strings.xml
If a field is null or empty, the details page will display a message to let the user know that all the available information is being displayed.
Jira ticket: https://onramp-training.atlassian.net/browse/TA2-89?atlOrigin=eyJpIjoiYjBiYWIwYWQ3M2QxNDRmY2JhYzVmMjlhNDk1OGJkZTAiLCJwIjoiaiJ9
> Null Messages

- app/src/main/java/com/example/voyagerx/LaunchDetailsFragment.kt
- app/src/main/java/com/example/voyagerx/adapters/LaunchCarouselAdapter.kt
- app/src/main/res/layout/fragment_launch_details.xml
The app now displays a filled in heart on the launch details page if that launch has been favorited by the current user.
I also modified the mission name text size to account for longer mission names. Previously the mission names were overlapping with the share/favorite buttons.
Jira ticket: https://onramp-training.atlassian.net/browse/TA2-42
Favorited launch:
Launch with long mission name:
> Display a user's favorite

- app/src/main/java/com/example/voyagerx/RegisterFragment.kt
- app/src/main/java/com/example/voyagerx/di/AppModule.kt
- app/src/main/java/com/example/voyagerx/repository/LaunchRepository.kt
- app/src/main/java/com/example/voyagerx/repository/SpaceXApiService.kt
- app/src/main/java/com/example/voyagerx/repository/UserRepository.kt
- app/src/main/java/com/example/voyagerx/repository/model/User.kt
> api service

- .idea/misc.xml
- app/src/main/java/com/example/voyagerx/MainActivity.kt
- app/src/main/res/values/strings.xml
Checks if user is logged in before navigating to profile page. If not, dialog prompts user to login/register. 
I'm using Celina's dialog right now, but I think the dialog function could be moved to the MainActivity after hers has been merged to prevent repeat code.
Sorry for laggy vid :( 
https://user-images.githubusercontent.com/103967461/167023082-f3ca5cf8-a87b-494b-8c45-a51afc62ef7b.mov
> checks user logged in when navigating to profile page

- app/src/main/java/com/example/voyagerx/LaunchDetailsFragment.kt
Created implicit intents for article and video links.
https://user-images.githubusercontent.com/41392379/167013650-c33f2a8f-0200-45a5-aa72-7e666103cbe3.mov
> Navigate to Article and Video Links

- app/src/main/java/com/example/voyagerx/LoginActivity.kt
- app/src/main/java/com/example/voyagerx/MainActivity.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/layout/fragment_login.xml
- app/src/main/res/layout/fragment_register.xml
- app/src/main/res/values/strings.xml
Added back button on login view to return to landing page. Changed colors on login view
https://user-images.githubusercontent.com/103967461/167005381-74fa88fc-9dab-4e98-abc3-1b9c2afe644a.mov
> Back Button On Login

- app/src/main/java/com/example/voyagerx/ui/fragments/userprofileac/FavoritesAdapter.kt
- app/src/main/java/com/example/voyagerx/ui/fragments/userprofileac/ProfileFragment.kt
On the user profile page, I have replaced the placeholder userObj with userRepository.getCurrentUser()? where appropriate and deleted the placeholder launch object.
> Deleting placeholder user/launch obj and calling from repo

- app/src/main/java/com/example/voyagerx/MainActivity.kt
When user logs out on profile page, they are redirected to the landing page.
> profile redirects to landing on logout

- app/src/main/java/com/example/voyagerx/adapters/LaunchCarouselAdapter.kt
- app/src/main/res/layout/fragment_launch_details.xml
Changed background color to secondary dark and text/icon colors to white. I also increased the line spacing for the details paragraph to increase readability.
https://user-images.githubusercontent.com/41392379/167192302-505e4146-793d-4d8e-83c6-cd1714939512.mov
> Detail Page Colors

- app/src/main/java/com/example/voyagerx/ui/fragments/userprofileac/FavoritesAdapter.kt
- app/src/main/java/com/example/voyagerx/ui/fragments/userprofileac/ProfileFragment.kt
This ticket covers navigating to the Details page upon clicking on a favorite within the Profile RecyclerView.
https://onramp-training.atlassian.net/jira/software/projects/TA2/boards/22?selectedIssue=TA2-52
https://user-images.githubusercontent.com/103965030/167172782-1127df5a-b078-442c-914b-637d6535d4cf.mov
> added navigation to details

- app/src/main/java/com/example/voyagerx/LaunchDetailsFragment.kt
- app/src/main/java/com/example/voyagerx/presenters/LaunchDetailsPresenter.kt
https://onramp-training.atlassian.net/browse/TA2-104
I created the `LaunchDetailsPresenter` to separate the business logic from the UI logic.
> Created launch details presenter

- app/src/main/res/layout/fragment_launch_details.xml
Changed color scheme back to white
> Re-do Launch Details color scheme

- app/src/main/java/com/example/voyagerx/ui/fragments/editprofile/EditProfileFragment.kt
Profile not updating quick enough when edited. Fix moves view transaction after edit profile edits user in database. Seems to be working but bug can be difficult to reproduce.
> Fixed Edit Profile Issue

- app/src/main/java/com/example/voyagerx/ui/fragments/editprofile/EditProfileFragment.kt
- app/src/main/res/layout/fragment_edit_profile.xml
This PR covers validating that the user name is not blank upon attempting to update user data in the database. I have also added maximum lengths to the edit text fields, so that the user cannot type indefinitely.
https://onramp-training.atlassian.net/jira/software/projects/TA2/boards/22?selectedIssue=TA2-108
https://user-images.githubusercontent.com/103965030/167901221-b0a0af98-1506-47a7-8917-5b510687676b.mov
> Edit profile data validation

- app/src/main/java/com/example/voyagerx/ui/fragments/editprofile/EditProfileFragment.kt
App is compiling and running on the emulator. Played around with edit profile screen and didn't see any bugs
> EditProfileFragment fix (missing currentUser initialization)

- app/src/main/java/com/example/voyagerx/MainActivity.kt
- app/src/main/res/values/strings.xml
Fixed bug with wrong profile dialog message. Also bug that does not redirect from edit profile page.
> Profile message and logout bug fixes

- app/src/main/java/com/example/voyagerx/ui/fragments/landing/list/LaunchOverviewAdapter.kt
- app/src/main/java/com/example/voyagerx/ui/fragments/userprofileac/FavoritesAdapter.kt
Sets the click handler on the card view of each favorites recycler view item instead of the item view. Ran into this same issue with the LaunchOverviewAdapter because of the ripple effect I added on the card.
> Favorites click not working
